version: '3'

services:
  mysql:
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: prismadev
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysqldev:/var/lib/mysql
    networks:
      - mysqldev-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysqldev-compose-network

  with-docker-multi-env-development:
    build:
      context: ../../
      dockerfile: docker/development/Dockerfile
    image: with-docker-multi-env-development
    ports:
      - '3001:3000'

networks:
  mysqldev-compose-network:
    driver: bridge

volumes: #define our mysql volume used above
  mysqldev:
