# Arquivo de Docker Nodejs Simples

# Dockerfile de contêiner duplo para processo de construção separado.

# Estamos começando com a mesma imagem base, mas estamos declarando
# que este bloco emite uma imagem chamada DEPS que nós
# não será implantado - ele apenas instala nossos Deps. de YARN
FROM node:16.15.0-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "dev" ]