version: '3.7'
services:
  mysql:
    container_name: mysql
    ports:
      - '3306:3306'
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: prisma
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - mysql-compose-network  

  # prisma:
  #   links:
  #     - mysql
  #   depends_on:
  #     - mysql
  #   container_name: prisma
  #   ports:
  #     - '5555:5555'
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dbprisma
  #   volumes:
  #     - .:/app
  #     - /app/prisma
  #   networks:
  #     - mysql-compose-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network

  backend:
    links:
      - mysql
    depends_on:
      - mysql
    container_name: backend
    ports:
      - '4000:4000'
    build:
      context: .
      dockerfile: Dockerfile.start
    volumes:
      - .:/app
      - /app/node_modules
      - /app/prisma
    networks:
      - mysql-compose-network

  frontend:
    container_name: frontend
    ports:
      - '3000:3000'
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge

volumes: #define our mysql volume used above
  mysql: