name: História de Usuário.
description: Essa issue é para escrever as histórias de usuário.
title: "[História de Usuário]: "
labels: ["userHistory"]
assignees:
  - BrunoCesarAngst
body:
  - type: markdown
    attributes:
      value: |
        História de Usuário é uma descrição concisa de uma necessidade do usuário do produto sob o ponto de vista deste usuário.
  - type: textarea
    id: user-story
    attributes:
      label: História de Usuário.
      description: O que o usuário quer fazer?
      placeholder: Coloque aqui as ações do usuário!
      value: "Como um <tipo de usuário>, eu quero <um objetivo> para que eu possa <benefício>."
      # render: Markdown
    validations:
      required: false
  - type: textarea
    id: act-user
    attributes:
      label: Ações do Usuário.
      description: O que o usuário espera que aconteça?
      placeholder: Coloque aqui as ações do usuário!
      # value: "- [ ] - "
      # render: Markdown
    validations:
      required: false
  - type: textarea
    id: act-sis
    attributes:
      label: Ações do Sistema.
      description: O que o sistema faz para estregar o que o usuário espera que aconteça?
      placeholder: Coloque aqui as ações do sistema!
      # value: "- [ ] - "
      # render: Markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Algum registo relevante (sh).
      description: Please copy and paste any relevant log output. Isso será formatado automaticamente em código. Portanto, não há necessidade de barra inversa.
      render: sh