name: User Story
# História de Usuário
description: File a user History
# Arquivar um histórico de Usuário
title: "[User History]: "
labels: ["userHistory"]
assignees:
  - BrunoCesarAngst
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this user history report!
  # Obrigado por ter tido tempo para preencher este relatório de histórico do utilizador!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      # Detalhes de contacto
      description: How can we get in touch with you if we need more info?
      # Como podemos entrar em contacto com você se precisarmos de mais informações?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      # o que aconteceu?
      description: Also tell us, what did you expect to happen?
      # Diga-nos também, o que esperava que acontecesse?
      placeholder: Tell us what you see!
      # Diga-nos o que vê!
      value: "A bug happened!"
      # Aconteceu um bug!
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      # Que versão do nosso software está a executar?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      # Em que navegadores está a ver o problema?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      # Saída de registo relevante
      description: Please copy and paste any relevant log output. Isso será formatado automaticamente em código. Portanto, não há necessidade de barra inversa.
      render: bash
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      # Código de Conduta
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      # Ao submeter esta questão, concorda em seguir o nosso [Código de Conduta](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
        # Eu concordo em seguir o código de conduta deste projeto
          required: true