name: Épico.
description: O épico representa uma parte integral do Produto e deve ser suficiente para ter valor de negócio em sua utilização.
title: "[Épico]: "
labels: ["Epic"]
assignees:
  - BrunoCesarAngst
body:
  - type: markdown
    attributes:
      value: |
        O Épico (Epic) é uma grande parte do trabalho a ser realizado no Produto. É também conhecido como uma Grande História de Usuário, da qual expressa de forma macro a necessidade global.
  - type: textarea
    id: user-story
    attributes:
      label: Épico.
      description: Épicos devem representar a entrega integral do Produto.
      placeholder: Coloque aqui algo sobre o épico!
      value: "Esse épico é ..."
      # render: Markdown
    validations:
      required: true