@startuml
skinparam monochrome reverse

left to right direction
actor "Usuário" as u
' actor "Sistema" as s
' actor "Banco de Dados" as b
rectangle Mysys {

  u -- (login)

  (login) <.u. (descrever uma informação): includes
  ' (descrever uma informação) <.. (recupera a informação): extends
  ' (recupera a informação) <.. (gravar informação): extends
  ' (recupera a informação) -- s
  ' (gerar listas das informações) ..> (recupera a informação): extends
  ' (gravar informação) -- s
  ' (gravar informação) -- b
  (login) <.. (interagir nas informações): includes
  ' (interagir nas informações) <.. (gerar listas das informações): extends
  ' (gerar listas das informações) -- s

  ' (login) -- s
  ' (logout) -- s

  u -- (logout)
}

@enduml
