@startuml

start
card **mySys** {
  package dashboard {
    floating note: O usuário quer ver itens capturados\nque não foram contextualizados
    split
    :informações de contextulização;
    stop
    split again
    :inbox;
    stop
    split again
    :capturar uma coisa;
    split again
    :acessar as listas;
    stop
    split again
    :fazer logout;
    stop
    end split
    package captura {
      :clicar em botão;
      package "criar uma coisa" {
        floating note: O usuário poderá criar um item:
        if (Quer intitular?) then (sim)
          ' :colocar um título;
          if (incluir áudios) then (sim)
            if (incluir fotos ) then (sim)
              if (incluir vídeo ) then (sim)
                if (incluir arquivos ) then (sim)
                else (não)
                endif
              else (não)
              endif
            else (não)
            endif
          else (não)
          endif
        else (não)
        endif
        repeat :descrever o item;
        repeat while (este item\nfoi descrito?) is (não)
        ->sim;
      }
    }
      if (quer contextualizar esse item?) then (sim)
        package "contextualizar item" {
          :contextualizar o item;
          stop
        }
      else (não)
      endif
    stop
  }
}
@enduml
